export const OPEN_API_ERRORS = {
  UNAUTHORIZED: 401,
  FORBIDDEN_SCOPE: 403,
  RATE_LIMITED: 429,
  VALIDATION_FAILED: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  CDK_INVALID: 400,
  CDK_IN_FLIGHT: 409,
  REDEEM_BLOCKED: 429,
  INTERNAL: 500,
} as const;

export type OpenApiErrorCode = keyof typeof OPEN_API_ERRORS;
